 platform :ios, '9.0'

target 'MasterGithub' do
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'SDWebImage'
  pod 'SnapKit'

  target 'MasterGithubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasterGithubUITests' do
    # Pods for testing
  end

end
